import React from 'react';
import { Helmet } from 'react-helmet';


const PrivacyPolicy = () => {
  return (
    <div className='res-extra-pdg max-w-[786px] privacy-policy mx-auto'>
      <Helmet>
        <title>Privacy Policy - Nipralo Technologies</title>
        <meta name="description" content="Learn about Nipralo Technologies' Privacy Policy, including how we collect, use, and protect your personal information." />
        <meta name="keywords" content="privacy policy, Nipralo Technologies, data protection, personal information, privacy" />
      </Helmet>
      <div className='heading pt-[100px] md:pt-[160px] border-b text-center pb-10'>
        <h1 className='font-light text-[40px] md:text-[52px] lg:text-[80px] '>Privacy Policy</h1>
      </div>

      <div className='pt-16 pb-20 md:pb-40'>
        <div>
          <p className="text-[#0c0c0d] leading-[1.5]">Last updated: August 22, 2024</p>
          <p className="text-[#0c0c0d] leading-[1.5]">This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use our services and informs you about your privacy rights and how the law protects you.</p>
          <p className="text-[#0c0c0d] leading-[1.5]">By using our services, you agree to the collection and use of information in accordance with this Privacy Policy.</p>
        </div>

        <div>
          <h2 className="text-[25.6px] md:text-[32px] font-light mt-10">Interpretation and Definitions</h2>
          <div>
            <h3 className="font-light text-[22.4px] md:text-[25.6px] mt-6">Interpretation</h3>
            <p className="text-[#0c0c0d] leading-[1.5]">Words with an initial capital letter have specific meanings defined under the following conditions. Definitions have the same meaning regardless of whether they appear in singular or plural form.</p>
          </div>
          <div>
            <h3 className="font-light text-[22.4px] md:text-[25.6px] mt-6">Definitions</h3>

            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Account</strong> means a unique account created for you to access our services or parts of our services.
            </li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Company</strong> (referred to as "the Company," "We," "Us," or "Our") refers to Nipralo Technologies, [Company Address], India.
            </li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Cookies</strong> are small files placed on your computer, mobile device, or any other device by a website, containing details of your browsing history on that website among other uses.
            </li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Country</strong> refers to India.
            </li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Device</strong> means any device that can access the services, such as a computer, cellphone, or digital tablet.
            </li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
            </li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Service</strong> refers to our website and any related services.
            </li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Service Provider</strong> means any natural or legal person who processes data on behalf of the Company. This includes third-party companies or individuals employed by the Company to facilitate the Service, perform services related to the Service, or assist in analyzing how the Service is used.
            </li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., duration of a page visit).
            </li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Website</strong> refers to Nipralo Technologies, accessible from [Your Website URL].
            </li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>You</strong> means the individual accessing or using the Service, or the company or legal entity on behalf of which the individual is accessing or using the Service, as applicable.
            </li>

          </div>
        </div>
        <div>
          <h2 className="text-[25.6px] md:text-[32px] font-light mt-10">Collecting and Using Your Personal Data</h2>
          <div>
            <h3 className="font-light text-[22.4px] md:text-[25.6px] mt-6">Types of Data Collected</h3>
            <h4 className="text-[20.8px] md:text-[22.4px] font-light mt-4">Personal Data</h4>
            <p className="text-[#0c0c0d] leading-[1.5]">While using our Service, we may ask you to provide certain personally identifiable information that can be used to contact or identify you. This may include:</p>
          </div>
          <div>

            <li className="text-[#0c0c0d] leading-[1.5]">Email address
            </li>
            <li className="text-[#0c0c0d] leading-[1.5]">First name and last name
            </li>
            <li className="text-[#0c0c0d] leading-[1.5]">Phone number
            </li>

          </div>
          <div>
            <h4 className="text-[20.8px] md:text-[22.4px] font-light mt-4">Usage Data</h4>
            <p className="text-[#0c0c0d] leading-[1.5]">Usage Data is collected automatically when using the Service. This may include:</p>

            <li className="text-[#0c0c0d] leading-[1.5]">Device's Internet Protocol address (e.g., IP address)</li>
            <li className="text-[#0c0c0d] leading-[1.5]">Browser type and version</li>
            <li className="text-[#0c0c0d] leading-[1.5]">Pages of our Service that you visit</li>
            <li className="text-[#0c0c0d] leading-[1.5]">Time and date of your visit</li>
            <li className="text-[#0c0c0d] leading-[1.5]">Time spent on those pages</li>
            <li className="text-[#0c0c0d] leading-[1.5]">Unique device identifiers and other diagnostic data</li>

            <p className="text-[#0c0c0d] leading-[1.5]">When accessing the Service through a mobile device, we may also collect information including but not limited to:</p>

            <li className="text-[#0c0c0d] leading-[1.5]">Type of mobile device used</li>
            <li className="text-[#0c0c0d] leading-[1.5]">Mobile device unique ID</li>
            <li className="text-[#0c0c0d] leading-[1.5]">IP address of the mobile device</li>
            <li className="text-[#0c0c0d] leading-[1.5]">Mobile operating system</li>
            <li className="text-[#0c0c0d] leading-[1.5]">Type of mobile Internet browser used</li>

          </div>
          <div>
            <h4 className="text-[20.8px] md:text-[22.4px] font-light mt-4">Tracking Technologies and Cookies</h4>
            <p className="text-[#0c0c0d] leading-[1.5]">We use cookies and similar tracking technologies to track activity on our Service and store certain information. Tracking technologies may include:</p>

            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Cookies:</strong> A small file placed on your Device. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some parts of our Service.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Flash Cookies:</strong> Local stored objects used to collect and store information about your preferences or activity. For more information on how to delete Flash Cookies, visit Adobe's guide.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Web Beacons:</strong> Small electronic files embedded in sections of our Service or emails to count users and gather related statistics.</li>

            <p className="text-[#0c0c0d] leading-[1.5]">When accessing the Service through a mobile device, we may also collect information including but not limited to:</p>

            <li className="text-[#0c0c0d] leading-[1.5]">Type of mobile device used</li>
            <li className="text-[#0c0c0d] leading-[1.5]">Mobile device unique ID</li>
            <li className="text-[#0c0c0d] leading-[1.5]">IP address of the mobile device</li>
            <li className="text-[#0c0c0d] leading-[1.5]">Mobile operating system</li>
            <li className="text-[#0c0c0d] leading-[1.5]">Type of mobile Internet browser used</li>

            <p className="text-[#0c0c0d] leading-[1.5]">Cookies can be Persistent or Session Cookies:</p>

            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Necessary / Essential Cookies:</strong> Used to provide services and authenticate users.</li>
            <li className="text-[#0c0c0d] leading-[1.5]">Cookies Policy / Notice Acceptance Cookies: Identify if users have accepted the use of cookies.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>Functionality Cookies:</strong> Remember choices you make to provide a more personalized experience.</li>

          </div>
          <div>
            <h3 className="font-light text-[22.4px] md:text-[25.6px] mt-6">Use of Your Personal Data</h3>
            <p className="text-[#0c0c0d] leading-[1.5]">We may use Personal Data for the following purposes:</p>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>To provide and maintain our Service,</strong> including monitoring usage.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>To manage your Account</strong> and provide access to different functionalities.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>For the performance of a contract</strong> or to provide services you have purchased.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>To contact you</strong> via email, telephone, or other electronic communications about updates, products, or services.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>To provide news,</strong> special offers, and information about similar goods and services unless you have opted out.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>To manage your requests</strong> and respond to inquiries.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>For business transfers</strong> in connection with mergers, sales, or acquisitions.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>For data analysis,</strong> improving our Service, and evaluating promotional campaigns.</li>

            <h3 className="font-light text-[22.4px] md:text-[25.6px] mt-6">Sharing Your Personal Data</h3>
            <p className="text-[#0c0c0d] leading-[1.5]">We may share your personal information in the following situations:</p>

            <li className="text-[#0c0c0d] leading-[1.5]"><strong>With Service Providers:</strong> To monitor, analyze usage, or contact you.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>For Business Transfers:</strong> In connection with mergers, asset sales, or business acquisitions.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>With Affiliates:</strong> Including our parent company or subsidiaries.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>With Business Partners:</strong> For specific products, services, or promotions.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>With Other Users:</strong> When interacting in public areas.</li>
            <li className="text-[#0c0c0d] leading-[1.5]"><strong>With Your Consent:</strong> For any other purposes with your approval.</li>

            <h3 className="font-light text-[22.4px] md:text-[25.6px] mt-6">Retention of Your Personal Data</h3>
            <p className="text-[#0c0c0d] leading-[1.5]">We retain your Personal Data only as necessary for the purposes outlined in this Privacy Policy and to comply with legal obligations.</p>
            <h3 className="font-light text-[22.4px] md:text-[25.6px] mt-6">Transfer of Your Personal Data</h3>
            <p className="text-[#0c0c0d] leading-[1.5]">Your information may be transferred to and maintained on computers located outside your jurisdiction. Your consent to this Privacy Policy signifies agreement to such transfers.</p>
            <h3 className="font-light text-[22.4px] md:text-[25.6px] mt-6">Disclosure of Your Personal Data</h3>
            <p className="text-[#0c0c0d] leading-[1.5]">We may disclose your Personal Data to:</p>

            <li className="text-[#0c0c0d] leading-[1.5]">Law Enforcement: If required by law or in response to valid requests by authorities.</li>
            <li className="text-[#0c0c0d] leading-[1.5]">Other Legal Requirements: To comply with legal obligations, protect rights, prevent wrongdoing, or protect safety.</li>

          </div>
          <div>
            <h3 className="font-light text-[22.4px] md:text-[25.6px] mt-6">Security of Your Personal Data</h3>
            <p className="text-[#0c0c0d] leading-[1.5]">We strive to use commercially acceptable means to protect your Personal Data, but no method of transmission over the Internet or electronic storage is 100% secure.</p>
            <h3 className="font-light text-[22.4px] md:text-[25.6px] mt-6">Children's Privacy</h3>
            <p className="text-[#0c0c0d] leading-[1.5]">Our Service does not target individuals under 13. If we collect Personal Data from a child under 13, we will take steps to remove it.</p>
            <h3 className="font-light text-[22.4px] md:text-[25.6px] mt-6">Links to Other Websites</h3>
            <p className="text-[#0c0c0d] leading-[1.5]">Our Service may contain links to other websites not operated by us. We are not responsible for the content or privacy policies of third-party sites.</p>
            <h3 className="font-light text-[22.4px] md:text-[25.6px] mt-6">Changes to this Privacy Policy</h3>
            <p className="text-[#0c0c0d] leading-[1.5]">We may update this Privacy Policy from time to time. Any changes will be posted on this page, and we will notify you via email or a prominent notice on our Service.</p>
            <h3 className="font-light text-[22.4px] md:text-[25.6px] mt-6">Contact Us</h3>
            <p className="text-[#0c0c0d] leading-[1.5]">If you have any questions about this Privacy Policy, you can contact us:</p>
            <li className="text-[#0c0c0d] leading-[1.5]">By email: <span className='underline underline-offset-1'><a href="mailto:info@nipralo.com">info@nipralo.com</a></span></li>
          </div>
        </div>
      </div>

    </div>
  )
}

export default PrivacyPolicy